//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int Idempresa { get; set; }
        public string RUC { get; set; }
        public string NomEmpresa { get; set; }
        public string Persona { get; set; }
        public Nullable<bool> Cuenta { get; set; }
        public string Celuar { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FecRegistro { get; set; }
        public Nullable<System.DateTime> UltMod { get; set; }
    }
}
