//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Usuario
    {
        public int idLog { get; set; }
        public string NomUsuario { get; set; }
        public string Ruc { get; set; }
        public string NomEmpresa { get; set; }
        public string Accion { get; set; }
        public Nullable<System.DateTime> FecAccion { get; set; }
    }
}
